brew: 0.0.1
name: zild
desc: Perl CPAN Zilla::Dist CLI

cmds:
  zild: /usr/local/bin/zild -v $PWD:/work

make:
  from: alpine:3.4
  pkgs:
  - bash
  - -build-base
  - -curl
  - git
  - openssl
  - -openssl-dev
  - perl
  - -perl-dev
  - -wget
  make:
  - cpanm: Zilla::Dist
  - rm: /root/.cpanm
  work: /work
  vars:
    PERL5LIB: /local
