brew: 0.0.1
name: sl
desc: Steam Locomotive

cmds:
  sl: /sl-cmd -it -e LINES=$LINES -e COLUMNS=$COLUMNS

make:
  from: alpine:3.4
  pkgs: [-build-base, -git, ncurses-dev]
  make:
  - repo: https://github.com/mtoyoda/sl
    cmds:
    - make
    - mv sl /sl-cmd
